name: icubmodelgeneratorenv
channels:
  - conda-forge
dependencies:
  - yarp
  - idyntree
  - python
  - pip
  - compilers
  - cmake
  - ninja
  - pkg-config
  - pyyaml=5
  - numpy
  - catkin_pkg
  - pip:
    - git+https://github.com/ros/urdf_parser_py@31474b9baaf7c3845b40e5a9aa87d5900a2282c3
    - git+https://github.com/robotology/simmechanics-to-urdf
